export default {
  LOGIN_FAILURE: 'LOGIN/FAILURE',
  REQUEST_DATA : 'REQUEST_DATA',
  RECEIVE_DATA : 'RECEIVE_DATA',
  LOADUSER_DATA: 'LOADUSER_DATA',
  RENT_DATA: 'RENT_DATA',
  DRIVER_DATA: 'DRIVER_DATA',
  VIO_DATA: 'VIO_DATA',
  VIOBASIC_DATA: 'VIOBASIC_DATA',
  MESSAGE_DATA: 'MESSAGE_DATA',
  MESSAGEUSER_DATA: 'MESSAGEUSER_DATA',
  USERMESSAGEUSER_DATA: 'USERMESSAGEUSER_DATA'
}
